### ISSUE TITLE
What version of nodejs is required to run mailit?

### ISSUE THREAD

**Issue by Naereen** [dthree/mailit#10]
Hi,
I installed your project on my Ubuntu with nodejs `v6.11.2` and npm `v5.3.0`, and encountered this issue:
```javascript
$ mailit --config config.json
/usr/lib/node_modules/mailit/src/routes.js:117
        app.post("/email", async (req, res) => {
                                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/mailit/index.js:10:16)
```

Is it a bug in mailit, or I am running a too old version of nodejs ?

**Comment by Naereen** [comment]
Thanks in advance! 🎩

**Comment by shashank34** [comment]
Hi Naereen 
node version above 7 is required

**Comment by Naereen** [comment]
OK. It could/should be written somewhere on the README.md ?

**Comment by ivanvs** [comment]
And we can maybe put that requirements in package.json file under [engines ](https://docs.npmjs.com/files/package.json#engines)property. 
So it would look like this:

`{ "engines" : { "node" : ">=7" } }`

What do you think about that?

**Comment by dthree** [comment]
@ivanvs sounds good. Feel free to do a PR.

**Comment by ivanvs** [comment]
@dthree nice to here that you like idea. I will make a PR after I finish my job tomorrow. Also I will add a notice into README.md file

**Comment by Naereen** [comment]
That's nice @ivanvs ... I would have said "@dthree, do it yourself, that's your project", but whatever.

**Comment by dthree** [comment]
@Naereen Wasn't trying to be rude. Contribution is what open source is all about. This project isn't some debt or obligation of mine, just something I wanted to share.

**Comment by shashank34** [comment]
@dthree  i appreciate it.

**Comment by ivanvs** [comment]
@dthree I think that we can close this issue. We have improved documentation and package.json, and that was desired improvement. What do you think about that?

**Comment by dthree** [comment]
K great, yes!
