### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by gregfr** [dthree/mailit#11]
Thanks for your contribution to OSS :)
What would think about email template? I.e. the service client would pass a template name and some variables to substitute, and the mailing service would send an email based on the template.
That would perfectly fit my needs.
Regards

**Comment by dthree** [comment]
Hi, and thanks!

I want to keep this service as simple as possible, and I believe this could be accomplished outside of `mailit` while still using it as a service. Does that sound okay?
