### ISSUE TITLE
Greeting never received

### ISSUE THREAD

**Issue by korrio** [dthree/mailit#7]
I've run this
curl --data "to=iamnotkorr@gmail.com&subject=hi&text=hey world" http://127.0.0.1:3000/email

And got
{"success":false,"status":503,"message":"Greeting never received"}

**Comment by dthree** [comment]
See this:

https://medium.com/@manojsinghnegi/sending-an-email-using-nodemailer-gmail-7cfa0712a799

**Comment by bamne123** [comment]
Can you explain what is the issue and the solution?
I am not able to make out anything from the post.
