### ISSUE TITLE
No SMTP auth

### ISSUE THREAD

**Issue by asatriani** [dthree/mailit#8]
Hi all,
I have problem sending email to internal SMTP server because it authenticate user/machine using only a white ip address list. Actualy user and pass config properties are required in mailit and that is not compatible with my SMTP server. I checked and in nodemailer createTransport method the auth section is optional. So I have modified routes.js and loadConfig.js and now send email is succesfull.
Do you think it can be a valid pull request? #9

**Comment by dthree** [comment]
Got it. We can totally fix this. Please see the note in the pull request.

**Comment by dthree** [comment]
I merged your PR!
